
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Aug 24 11:48:26 CEST 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACE = 7;
  public static final int CHARACTER = 12;
  public static final int IDENT = 9;
  public static final int BOOL = 11;
  public static final int NUMBER = 10;
  public static final int SEMI = 4;
  public static final int PROG = 2;
  public static final int EOF = 0;
  public static final int ASSIGN = 6;
  public static final int error = 1;
  public static final int COMMA = 5;
  public static final int RBRACE = 8;
  public static final int CONST = 3;
}

