
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Aug 27 19:17:26 CEST 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MAP = 16;
  public static final int CONST = 3;
  public static final int LPAREN = 39;
  public static final int SEMI = 34;
  public static final int CONTINUE = 12;
  public static final int FOR = 13;
  public static final int MINUS = 18;
  public static final int CHARACTER = 48;
  public static final int RPAREN = 40;
  public static final int AND = 28;
  public static final int LT = 26;
  public static final int OR = 29;
  public static final int BOOL = 47;
  public static final int COMMA = 36;
  public static final int INC = 32;
  public static final int DIV = 20;
  public static final int GEQ = 25;
  public static final int PLUS = 17;
  public static final int ASSIGN = 31;
  public static final int IF = 9;
  public static final int DOT = 37;
  public static final int FINDANY = 15;
  public static final int EOF = 0;
  public static final int RETURN = 8;
  public static final int NEW = 4;
  public static final int error = 1;
  public static final int MUL = 19;
  public static final int NUMBER = 46;
  public static final int MOD = 21;
  public static final int NEQ = 23;
  public static final int IDENT = 45;
  public static final int BREAK = 11;
  public static final int VOID = 7;
  public static final int EQ = 22;
  public static final int LBRACK = 41;
  public static final int ARROW = 30;
  public static final int COLON = 35;
  public static final int LBRACE = 43;
  public static final int ELSE = 10;
  public static final int RBRACK = 42;
  public static final int READ = 6;
  public static final int RBRACE = 44;
  public static final int PROG = 2;
  public static final int LEQ = 27;
  public static final int QUESTION = 38;
  public static final int DEC = 33;
  public static final int GT = 24;
  public static final int PRINT = 5;
  public static final int LENGTH = 14;
}

