
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Aug 22 13:22:32 CEST 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PROG = 2;
  public static final int error = 1;
  public static final int IDENT = 3;
  public static final int EOF = 0;
}

