package rs.ac.bg.etf.pp1;

import java_cup.runtime.*;
import org.apache.log4j.*;
import rs.ac.bg.etf.pp1.ast.*;

parser code {:

	boolean errorDetected;

	Logger log = Logger.getLogger(getClass());
   
   
    // slede redefinisani metodi za prijavu gresaka radi izmene teksta poruke
     
    public void report_fatal_error(String message, Object info) throws java.lang.Exception {
      done_parsing();
      report_error(message, info);
    }
  
    public void syntax_error(Symbol cur_token) {
        report_error("\nSintaksna greska", cur_token);
    }
  
    public void unrecovered_syntax_error(Symbol cur_token) throws java.lang.Exception {
        report_fatal_error("Fatalna greska, parsiranje se ne moze nastaviti", cur_token);
    }

    public void report_error(String message, Object info) {
    	errorDetected = true;
    	StringBuilder msg = new StringBuilder(message); 
    	if (info instanceof Symbol)
            msg.append (" na liniji ").append(((Symbol)info).left);
        log.error(msg.toString());
    }


:}


init with {:
	errorDetected = false;
:}

scan with {:
	Symbol s = this.getScanner().next_token();
	if (s != null && s.value != null) 
		log.info(s.toString() + " " + s.value.toString());
	return s;
:}


terminal PROG, CONST, SEMI, COMMA, ASSIGN, LBRACE, RBRACE, LBRACKET, RBRACKET;
terminal String IDENT;
terminal Integer NUMBER, BOOL;
terminal Character CHARACTER;

nonterminal Program Program;
nonterminal ProgramName ProgramName;
nonterminal ConstVarDeclList ConstVarDeclList;
nonterminal ConstDeclList ConstDeclList;
nonterminal VarDeclList VarDeclList;
nonterminal VarList VarList;
nonterminal VarItem VarItem;
nonterminal Type Type;
nonterminal ConstList ConstList;
nonterminal ConstItem ConstItem;
nonterminal Constant Constant;
nonterminal MethodDeclList MethodDeclList;
nonterminal MethodDecl MethodDecl;


/* Program = "program" ident {ConstDecl | VarDecl } "{" {MethodDecl} "}". */

Program ::= (Program) PROG ProgramName:P1 ConstVarDeclList:C2 LBRACE MethodDeclList:M3 RBRACE {: RESULT=new Program(P1, C2, M3); RESULT.setLine(P1left); :};

ProgramName ::= (ProgramName) IDENT:I1 {: RESULT=new ProgramName(I1); RESULT.setLine(I1left); :};

ConstVarDeclList ::= 	(ConstVarDeclList_const) ConstVarDeclList:C1 ConstDeclList:C2 {: RESULT=new ConstVarDeclList_const(C1, C2); RESULT.setLine(C1left); :}
						| 
						(ConstVarDeclList_var) ConstVarDeclList:C1 VarDeclList:V2 {: RESULT=new ConstVarDeclList_var(C1, V2); RESULT.setLine(C1left); :}
						|
						(ConstVarDeclList_epsilon) {: RESULT=new ConstVarDeclList_epsilon(); :} /* epsilon */
						;

/* const int x = 1; const int y = 2, z = 3; */

ConstDeclList ::= (ConstDeclList) CONST Type:T1 ConstList:C2 SEMI {: RESULT=new ConstDeclList(T1, C2); RESULT.setLine(T1left); :};

Type ::= (Type) IDENT:I1 {: RESULT=new Type(I1); RESULT.setLine(I1left); :};

ConstList ::= 	(ConstList_multiple) ConstList:C1 COMMA ConstItem:C2 {: RESULT=new ConstList_multiple(C1, C2); RESULT.setLine(C1left); :}
				|
				(ConstList_single) ConstItem:C1 {: RESULT=new ConstList_single(C1); RESULT.setLine(C1left); :}
				;
				
ConstItem ::= (ConstItem) IDENT:I1 ASSIGN Constant:C2 {: RESULT=new ConstItem(I1, C2); RESULT.setLine(I1left); :};
				
Constant ::= 	(Constant_number) NUMBER:N1 {: RESULT=new Constant_number(N1); RESULT.setLine(N1left); :}
				|
				(Constant_character) CHARACTER:C1 {: RESULT=new Constant_character(C1); RESULT.setLine(C1left); :}
				|
				(Constant_bool) BOOL:B1 {: RESULT=new Constant_bool(B1); RESULT.setLine(B1left); :}
				;
				
VarDeclList ::= (VarDeclList) Type:T1 VarList:V2 SEMI {: RESULT=new VarDeclList(T1, V2); RESULT.setLine(T1left); :};

VarList ::= (VarList_multiple) VarList:V1 COMMA VarItem:V2 {: RESULT=new VarList_multiple(V1, V2); RESULT.setLine(V1left); :}
			|
			(VarList_single) VarItem:V1 {: RESULT=new VarList_single(V1); RESULT.setLine(V1left); :}
			;
			
VarItem ::= (VarItem_var) IDENT:I1 {: RESULT=new VarItem_var(I1); RESULT.setLine(I1left); :}
			|
			(VarItem_array) IDENT:I1 LBRACKET RBRACKET {: RESULT=new VarItem_array(I1); RESULT.setLine(I1left); :}
			;
				
MethodDeclList ::=  (MethodDeclList_methods) MethodDeclList:M1 MethodDecl:M2 {: RESULT=new MethodDeclList_methods(M1, M2); RESULT.setLine(M1left); :}
					|
					(MethodDeclList_epsilon) {: RESULT=new MethodDeclList_epsilon(); :}  /* epsilon */
					;


							
			








