package rs.ac.bg.etf.pp1;

import java_cup.runtime.*;
import org.apache.log4j.*;
import rs.ac.bg.etf.pp1.ast.*;

parser code {:

	boolean errorDetected;

	Logger log = Logger.getLogger(getClass());
   
   
    // slede redefinisani metodi za prijavu gresaka radi izmene teksta poruke
     
    public void report_fatal_error(String message, Object info) throws java.lang.Exception {
      done_parsing();
      report_error(message, info);
    }
  
    public void syntax_error(Symbol cur_token) {
        report_error("\nSintaksna greska", cur_token);
    }
  
    public void unrecovered_syntax_error(Symbol cur_token) throws java.lang.Exception {
        report_fatal_error("Fatalna greska, parsiranje se ne moze nastaviti", cur_token);
    }

    public void report_error(String message, Object info) {
    	errorDetected = true;
    	StringBuilder msg = new StringBuilder(message); 
    	if (info instanceof Symbol)
            msg.append (" na liniji ").append(((Symbol)info).left);
        log.error(msg.toString());
    }


:}


init with {:
	errorDetected = false;
:}

scan with {:
	Symbol s = this.getScanner().next_token();
	if (s != null && s.value != null) 
		log.info(s.toString() + " " + s.value.toString());
	return s;
:}


terminal PROG, CONST, SEMI, COMMA, ASSIGN, LBRACE, RBRACE;
terminal String IDENT;
terminal Integer NUMBER, BOOL;
terminal Character CHARACTER;

nonterminal Program, ProgramName, ConstVarDeclList, ConstDeclList, VarDeclList, Type, ConstList, ConstItem, Constant;
nonterminal MethodDeclList, MethodDecl;


/* Program = "program" ident {ConstDecl | VarDecl } "{" {MethodDecl} "}". */

Program ::= (Program) PROG ProgramName ConstVarDeclList LBRACE MethodDeclList RBRACE;

ProgramName ::= (ProgramName) IDENT;

ConstVarDeclList ::= 	(ConstVarDeclList_const) ConstVarDeclList ConstDeclList
						| 
						(ConstVarDeclList_var) ConstVarDeclList VarDeclList
						|
						(ConstVarDeclList_epsilon) /* epsilon */
						;

/* const int x = 1; const int y = 2, z = 3; */

ConstDeclList ::= (ConstDeclList) CONST Type ConstList SEMI;

Type ::= (Type) IDENT;

ConstList ::= 	(ConstList_multiple) ConstList COMMA ConstItem
				|
				(ConstList_single) ConstItem
				;
				
ConstItem ::= (ConstantAssign) IDENT ASSIGN Constant;
				
Constant ::= 	(Constant_number) NUMBER
				|
				(Constant_character) CHARACTER
				|
				(Constant_bool) BOOL
				;
				
MethodDeclList ::= MethodDeclList MethodDecl
					|
					MethodDecl
					|
					/* epsilon */
					;


							
			








